export const AllergyTips = [
  { id: 1, tip: "Check pollen counts on your app in the morning and try to stay indoors when they're high." },
  { id: 2, tip: "Know exactly what you're allergic to & avoid those pollen types by checking your pollen forecast app levels." },
  { id: 3, tip: "Know your allergy triggers. Create a calendar of symptoms in your app & check pollen forecast." },
  { id: 4, tip: "After being outdoors, take a shower & change your clothes to wash away any allergens." },
  { id: 5, tip: "If the pollen count is high, keep the windows and doors closed to protect your indoor air." },
  { id: 6, tip: "Fine-tune your fitness routine. Morning exercisers hit hardest generally by airborne allergen. Consider indoor workouts." },
  { id: 7, tip: "To avoid ragweed season, consider a vacation in late summer & early fall as the weather cools." },
  { id: 8, tip: "Consider showering in the evening to wash off any pollen stuck to the body before bedtime." },
  { id: 9, tip: "Workout outside? Consider an asphalt tennis court, school track, or swimming pool instead of grassy areas." },
  { id: 10, tip: "Wearing wraparound or oversized sunglasses can help reduce pollen contact with the eyes." },
  { id: 11, tip: "When you get back from a walk, change into a clean set of clothes." },
  { id: 12, tip: "Protect your bed. Encase pillows in allergen-proof covers and wash your hair before bed to avoid pollen on pillows." },
  { id: 13, tip: "Avoidance is your best strategy as there is still no cure for seasonal allergies." },
  { id: 14, tip: "On peak pollen days, stay indoors while the sun's up. Walk or run in the evening instead." },
  { id: 15, tip: "Keep car windows and sunroofs closed. Recirculate air instead of using the vent which lets in pollen." },
  { id: 16, tip: "Invest in a HEPA air purifier. Regularly change filters in your furnace and air conditioner." },
  { id: 17, tip: "Wear a pollen mask if you do outdoor chores." },
  { id: 18, tip: "Delegate lawn mowing, weed pulling and gardening chores to others to avoid stirring up allergens." },
  { id: 19, tip: "During allergy season, ban pets from your bedroom or at least keep them off furniture as they track pollen." },
  { id: 20, tip: "Stay hydrated. Fluids help thin mucus and hydrate airways, making breathing easier." },
  { id: 21, tip: "Clean floors often with a vacuum cleaner that has a HEPA filter to get rid of pollen from outdoors." },
  { id: 22, tip: "Avoid outdoor activity in the early morning when pollen counts are highest." },
  { id: 23, tip: "Stay indoors on dry, windy days." },
  { id: 24, tip: "Remove your shoes outside and place clothes in the hamper to avoid spreading allergens indoors." },
  { id: 25, tip: "The best time to go outside is after a good rain, which clears pollen from the air." },
  { id: 26, tip: "Trim your lawn. Shorter blades won't trap as much pollen from trees and flowers." },
  // { id: 27, tip: "Consider switching from carpet to hardwood or tile flooring, which are easier to clean and less allergen-prone." },
  { id: 28, tip: "Avoid drying laundry outside on high pollen count days." },
  { id: 29, tip: "Keep indoor air clean using a portable HEPA filter in your bedroom." },
  { id: 30, tip: "Fine-tune your fitness routine. Indoor workouts are better when pollen is high." },
  { id: 31, tip: "Put Vaseline around your nostrils to trap pollen." },
  { id: 32, tip: "Limit close contact with pets that spend a lot of time outdoors." },
  { id: 33, tip: "Wash bed sheets frequently in summer to ease allergy symptoms and sleep better." },
  { id: 34, tip: "Get lots of rest to minimize allergy effects and feel better." },
  { id: 35, tip: "Rinse your nasal passages daily during pollen season." },
  { id: 36, tip: "Gargling with salt water can soothe a sore or scratchy throat." },
  { id: 37, tip: "Avoid alcohol during peak hay fever season as it may worsen allergy symptoms." },
  { id: 38, tip: "If your child played outside, have them bathe right away to reduce allergy triggers." },
  { id: 39, tip: "Using air conditioning in your house and car helps reduce mold and pollen." },
  { id: 40, tip: "Take your shoes off at the door to avoid tracking pollen inside." }
];
